---
# tasks file for prerequisite

- name: install tools
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - zsh
    - docker.io
    - python-pip
    - curl

- name: Zsh conf
  template: src=bashrc.j2 dest=/root/.bashrc owner=root group=root

- name: check go extraction
  stat: path=/opt/go/bin/go
  register: go_installed

# Install GO

- name : download {{ go }}
  get_url: url=https://storage.googleapis.com/golang/{{ go }}.tar.gz dest=/tmp/{{ go }}.tar.gz validate_certs=no
  when: not go_installed.stat.exists and not go_installed.stat.exists

- name: check go extraction
  stat: path=/tmp/{{ go }}
  register: go_extracted

- name: unarchive go
  unarchive: src=/tmp/{{ go }}.tar.gz dest=/opt copy=no
  when: not go_installed.stat.exists and not go_extracted.stat.exists

- name: clone fabric
  git: repo=https://github.com/hyperledger/fabric.git dest=/root/fabric

- name: Install docker-py (to pull docker images)
  pip: name=docker-py

- name: pull hyperledger fabric docker images
  docker_image: name={{ item }} tag=x86_64-1.0.0-alpha
  with_items:
    - hyperledger/fabric-ca
    - hyperledger/fabric-couchdb
    - hyperledger/fabric-kafka
    - hyperledger/fabric-zookeeper
    - hyperledger/fabric-orderer
    - hyperledger/fabric-peer
    - hyperledger/fabric-javaenv
    - hyperledger/fabric-ccenv

- name: download fabric-sample
  get_url:
    url: https://nexus.hyperledger.org/content/repositories/snapshots/sandbox/vex-yul-hyp-jenkins-2/fabric-binaries/release.tar.gz
    dest: /root/fabric-sample

# - unarchive:
#     chdir: /root/fabric-sample
#     src: release.tar.gz
#     dest: /root/fabric-sample/
